version: '3'

services:
  proxy:
    image: haproxy
    build:
      context: ./Proxy
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mainweb
      - mainapi

  mainweb:
    image: mainweb
    build:
      context: ./MainWeb
      dockerfile: Dockerfile
    depends_on:
      - mainapi

  mainapi:
    image: mainapi
    build:
      context: ./MainApi
      dockerfile: Dockerfile