version: '3'

services:

  mainweb:
    image: mainweb
    build:
      context: ./MainWeb
      dockerfile: Dockerfile
    depends_on:
      - mainapi
    hostname: web
    domainname: saachiroye.local
    links:
      - mainapi:mainapi
    ports: 
      - "80:80"

  mainapi:
    image: mainapi
    build:
      context: ./MainApi
      dockerfile: Dockerfile
    hostname: services
    domainname: saachiroye.local
    ports:
      - "81:80"