version: '3'

services:

  mainweb:
    image: mainweb
    build:
      context: ./MainWeb
      dockerfile: Dockerfile
    depends_on:
      - mainapi
    ports:
      - "50000:50000"

  mainapi:
    image: mainapi
    build:
      context: ./MainApi
      dockerfile: Dockerfile
    ports:
      - "50001:50001"